In [1]:
import numpy as np
a=np.random.randint(1,15,12)
#will return any 12 number between 1 to 15. Each time on running ,these values will change.
print(a)
print('----------------------------------------')

[ 8  6 14 10  1 14  3  9  8  8  8 11]
----------------------------------------


In [2]:
b=a.shape #return number of rows and number of columns.
print(b)

(12,)


In [3]:
print('----------------------------------------')
a=a.reshape(3,4)
#convert 1D array into 2D array and total num should be equal to total elements in 1D array 3*2=12.
print(a)
print('----------------------------------------')

----------------------------------------
[[ 8  6 14 10]
 [ 1 14  3  9]
 [ 8  8  8 11]]
----------------------------------------


In [4]:
a=a.reshape(6,2) #6*2=12
print(a)
print('----------------------------------------')
a=a.reshape(2,6) #2*6=12
print(a)
print('----------------------------------------')
a=a.reshape(1,12)
print(a)
print('----------------------------------------')
print(a.ndim)
a=a.reshape(12) #convert 2D INTO 1D
print(a)
print('----------------------------------------')

[[ 8  6]
 [14 10]
 [ 1 14]
 [ 3  9]
 [ 8  8]
 [ 8 11]]
----------------------------------------
[[ 8  6 14 10  1 14]
 [ 3  9  8  8  8 11]]
----------------------------------------
[[ 8  6 14 10  1 14  3  9  8  8  8 11]]
----------------------------------------
2
[ 8  6 14 10  1 14  3  9  8  8  8 11]
----------------------------------------


In [5]:
a=a.reshape(2,2,3) #3D conversion
print(a)
print('----------------------------------------')
print(a.ndim) #shows dimentions of given array.
print('----------------------------------------')

[[[ 8  6 14]
  [10  1 14]]

 [[ 3  9  8]
  [ 8  8 11]]]
----------------------------------------
3
----------------------------------------


In [6]:
a=a.reshape(4,-1)
# convert into 2D array, row would be 4 and column would be 12/4 =3. so -1 will be replaced by 3.
print(a)
print('----------------------------------------')
a=a.reshape(6,-1)
# convert into 2D array, row would be 6 and column would be 12/6 =2. so -1 will be replaced by 2.
print(a)
print('----------------------------------------')
a=a.reshape(2,-1)
print(a)
print('----------------------------------------')

[[ 8  6 14]
 [10  1 14]
 [ 3  9  8]
 [ 8  8 11]]
----------------------------------------
[[ 8  6]
 [14 10]
 [ 1 14]
 [ 3  9]
 [ 8  8]
 [ 8 11]]
----------------------------------------
[[ 8  6 14 10  1 14]
 [ 3  9  8  8  8 11]]
----------------------------------------


In [7]:
a=a.reshape(-1,4)
# convert into 2D array, column would be 4 and row would be 12/4 =3. so -1 will be replaced by 3.
print(a)
print('----------------------------------------')
a=a.reshape(-1,2)
print(a)
print('----------------------------------------')
a=a.reshape(-1,3)
print(a)

[[ 8  6 14 10]
 [ 1 14  3  9]
 [ 8  8  8 11]]
----------------------------------------
[[ 8  6]
 [14 10]
 [ 1 14]
 [ 3  9]
 [ 8  8]
 [ 8 11]]
----------------------------------------
[[ 8  6 14]
 [10  1 14]
 [ 3  9  8]
 [ 8  8 11]]
